style"frame"{
xthickness=0
ythickness=0
engine"pixmap"{
image{
function=SHADOW_GAP
file="images/arrow-bg.svg"
border={4,4,4,4}
stretch=TRUE
gap_start_file="images/none.svg"
gap_start_border={0,0,0,0}
gap_end_file="images/none.svg"
gap_end_border={0,0,0,0}
gap_file="images/none.svg"
}}}class"GtkFrame"style"frame"
