style"menu"{
bg[NORMAL]=shade(0.85,@bg_color)}
widget"*GtkWindow.gtk-combobox-popup-menu*"style"menu"
widget"*GtkMenu"style"menu"
widget_class"*<GtkMenu>*"style"menu"
style"menuitem"{
ythickness=3
bg[PRELIGHT]=@selected_bg_color}
widget_class"*.<GtkMenu>.<GtkMenuItem>"style"menuitem"
style"menuitem"{
fg[PRELIGHT]=@selected_fg_color}
widget_class"*.<GtkMenu>.<GtkMenuItem>.<GtkLabel>"style"menuitem"

style"menuseperator"{
xthickness=0
ythickness=1
GtkSeparatorMenuItem::horizontal-padding=0
GtkMenuItem::toggle-spacing=0
GtkWidget::wide-separators=1
GtkMenuItem::separator-height=1
GtkMenu::shadow-type=GTK_SHADOW_NONE
engine"pixmap"{
image{
function=BOX
file="images/line.svg"
border={1,0,0,0}
stretch=TRUE}}}
widget_class"*<GtkSeparatorMenuItem>*"style"menuseperator"

style"gtkmenucheckbutton"{
xthickness=1
ythickness=1
GtkCheckButton::indicator-size=18
GtkRadioButton::indicator-size=18
GtkCheckMenuItem::indicator-size=18
GtkRadioMenuItem::indicator-size=18
engine"pixmap"{
image{
function=CHECK
state=INSENSITIVE
shadow=OUT
file="images/menu_check_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/none.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=NORMAL
shadow=OUT
file="images/menu_check_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/none.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=PRELIGHT
shadow=OUT
file="images/menu_check_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/none.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=ACTIVE
shadow=OUT
file="images/menu_check_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/none.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=INSENSITIVE
shadow=ETCHED_IN
file="images/menu_check_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/check-semi_insensitive.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=NORMAL
shadow=ETCHED_IN
file="images/menu_check_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/check-semi.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=PRELIGHT
shadow=ETCHED_IN
file="images/menu_check_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/check-semi.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=ACTIVE
shadow=ETCHED_IN
file="images/menu_check_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/check-semi.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=INSENSITIVE
shadow=ETCHED_OUT
file="images/menu_check_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/check-semi_insensitive.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=NORMAL
shadow=ETCHED_OUT
file="images/menu_check_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/check-semi.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=PRELIGHT
shadow=ETCHED_OUT
file="images/menu_check_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/check-semi.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=ACTIVE
shadow=ETCHED_OUT
file="images/menu_check_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/check-semi.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=INSENSITIVE
shadow=IN
file="images/menu_check_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/check-check_insensitive.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=NORMAL
shadow=IN
file="images/tab_active.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/check-check.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=PRELIGHT
shadow=IN
file="images/tab_active.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/check-check.svg"
overlay_stretch=FALSE}
image{
function=CHECK
state=ACTIVE
shadow=IN
file="images/tab_active.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/check-check.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=INSENSITIVE
shadow=OUT
file="images/menu_radio_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/none.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=NORMAL
shadow=OUT
file="images/menu_radio_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/none.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=PRELIGHT
shadow=OUT
file="images/menu_radio_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/none.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=ACTIVE
shadow=OUT
file="images/menu_radio_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/none.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=INSENSITIVE
shadow=ETCHED_IN
file="images/menu_radio_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/radio-semi_insensitive.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=NORMAL
shadow=ETCHED_IN
file="images/menu_radio_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/radio-semi.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=PRELIGHT
shadow=ETCHED_IN
file="images/menu_radio_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/radio-semi.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=ACTIVE
shadow=ETCHED_IN
file="images/menu_radio_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/radio-semi.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=INSENSITIVE
shadow=ETCHED_OUT
file="images/menu_radio_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/radio-semi_insensitive.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=NORMAL
shadow=ETCHED_OUT
file="images/menu_radio_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/radio-semi.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=PRELIGHT
shadow=ETCHED_OUT
file="images/menu_radio_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/radio-semi.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=ACTIVE
shadow=ETCHED_OUT
file="images/menu_radio_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/radio-semi.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=INSENSITIVE
shadow=IN
file="images/menu_radio_normal.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/radio-check_insensitive.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=NORMAL
shadow=IN
file="images/radio_active.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/radio-check.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=PRELIGHT
shadow=IN
file="images/radio_active.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/radio-check.svg"
overlay_stretch=FALSE}
image{
function=OPTION
state=ACTIVE
shadow=IN
file="images/radio_active.svg"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/radio-check.svg"
overlay_stretch=FALSE}}}
class"GtkMenu*"style"gtkmenucheckbutton"
