#fixme add transparent border to outside and inside to remove double borders!

style"gtknotebook"{
xthickness=1
ythickness=1
GtkNotebook::tab-curvature=40
GtkNotebook::tab-overlap=1
GtkNotebook::has-backward-stepper=0
GtkNotebook::has-forward-stepper=1
GtkNotebook::has-secondary-backward-stepper=1
GtkNotebook::has-secondary-forward-stepper=0
engine"pixmap"{
image{
function=SHADOW
file="images/none.svg"
stretch=FALSE}
image{
function=BOX_GAP
file="images/shadow.svg"
detail="notebook"
border={1,1,1,1}
stretch=TRUE
gap_file="images/line.svg"
gap_border={0,0,0,0}}
image{
function=EXTENSION
state=ACTIVE
file="images/tab-top_normal.svg"
border={2,2,13,13}
stretch=TRUE
gap_side=BOTTOM}
image{
function=EXTENSION
file="images/tab-top_active.svg"
border={2,2,13,13}
stretch=TRUE
gap_side=BOTTOM}
image{
function=EXTENSION
state=ACTIVE
file="images/tab-bottom_normal.svg"
border={2,2,13,13}
stretch=TRUE
gap_side=TOP}
image{
function=EXTENSION
file="images/tab-bottom_active.svg"
border={2,2,13,13}
stretch=TRUE
gap_side=TOP}
image{
function=EXTENSION
state=ACTIVE
file="images/tab-right_normal.svg"
border={13,13,2,2}
stretch=TRUE
gap_side=LEFT}
image{
function=EXTENSION
file="images/tab-right_active.svg"
border={13,13,2,2}
stretch=TRUE
gap_side=LEFT}
image{
function=EXTENSION
state=ACTIVE
file="images/tab-left_normal.svg"
border={13,13,2,2}
stretch=TRUE
gap_side=RIGHT}
image{
function=EXTENSION
file="images/tab-left_active.svg"
border={13,13,2,2}
stretch=TRUE
gap_side=RIGHT
}}}class"GtkNotebook"style"gtknotebook"


