style "scrollbar"{
bg[NORMAL]=@selected_bg_color
bg[PRELIGHT]=@selected_bg_color
bg[SELECTED]=@selected_bg_color
bg[ACTIVE]=shade (0.6, @bg_color)
bg[INSENSITIVE]=@base_color
xthickness=0
ythickness=0
GtkScrollbar::min-slider-length=40
GtkScrollbar::fixed-slider-length=1
GtkScrollbar::has_secondary_backward_stepper=0
GtkScrollbar::has_secondary_forward_stepper=0
GtkScrollbar::has_backward_stepper=1
GtkScrollbar::has_forward_stepper=1
GtkRange::activate-slider=0
GtkRange::slider-width=18
GtkRange::stepper-size=18
GtkRange::stepper-spacing=0
GtkRange::trough-border=0
GtkRange::trough-under-steppers=1
engine"pixmap"
{
image
{
function=BOX
orientation=VERTICAL
detail="trough"
file="images/scrollbar.svg"
border={1,1,1,1}
stretch=TRUE
}
image
{
function=BOX
orientation=HORIZONTAL
detail="trough"
file="images/scrollbar.svg"
border={1,1,1,1}
stretch=TRUE
}
image
{
function=SLIDER
state=NORMAL
orientation=VERTICAL
file="images/selection-color.svg"
stretch=FALSE
overlay_file="images/shadow.svg"
overlay_stretch=TRUE
overlay_border={1,1,1,1}
}
image
{
function=SLIDER
state=NORMAL
orientation=HORIZONTAL
file="images/selection-color.svg"
stretch=FALSE
overlay_file="images/shadow.svg"
overlay_stretch=TRUE
overlay_border={1,1,1,1}
}
image
{
function=SLIDER
state=INSENSITIVE
orientation=VERTICAL
file="images/window-color.svg"
stretch=FALSE
overlay_file="images/shadow.svg"
overlay_stretch=TRUE
overlay_border={1,1,1,1}
}
image
{
function=SLIDER
state=INSENSITIVE
orientation=HORIZONTAL
file="images/window-color.svg"
stretch=FALSE
overlay_file="images/shadow.svg"
overlay_stretch=TRUE
overlay_border={1,1,1,1}}}}
class"GtkScrollbar"style"scrollbar"


style"notebookscrolledwindowscrollbar"{
engine"pixmap"
{
image
{
function=BOX
orientation=VERTICAL
detail="trough"
file="images/scrollbar_vertical-rightopen.svg"
border={1,1,1,1}
stretch=TRUE
}
image
{
function=BOX
orientation=HORIZONTAL
detail="trough"
file="images/scrollbar_horizontal-bottomopen.svg"
border={1,1,1,1}
stretch=TRUE
}
image
{
function=SLIDER
state=NORMAL
orientation=VERTICAL
file="images/selection-color.svg"
stretch=FALSE
overlay_file="images/shadow.svg"
overlay_stretch=TRUE
overlay_border={1,1,1,1}
}
image
{
function=SLIDER
state=NORMAL
orientation=HORIZONTAL
file="images/selection-color.svg"
stretch=FALSE
overlay_file="images/shadow.svg"
overlay_stretch=TRUE
overlay_border={1,1,1,1}
}
image
{
function=SLIDER
state=INSENSITIVE
orientation=VERTICAL
file="images/window-color.svg"
stretch=FALSE
overlay_file="images/shadow.svg"
overlay_stretch=TRUE
overlay_border={1,1,1,1}
}
image
{
function=SLIDER
state=INSENSITIVE
orientation=HORIZONTAL
file="images/window-color.svg"
stretch=FALSE
overlay_file="images/shadow.svg"
overlay_stretch=TRUE
overlay_border={1,1,1,1}}}}
widget_class"*GtkNotebook.GtkScrolledWindow.GtkHScrollbar"style"notebookscrolledwindowscrollbar"
widget_class"*GtkNotebook.GtkScrolledWindow.GtkVScrollbar"style"notebookscrolledwindowscrollbar"
widget_class"*GtkNotebook.GimpDisplayShell.GtkHBox.GtkVBox.GtkVScrollbar"style"notebookscrolledwindowscrollbar"
widget_class"*GtkNotebook.GtkVBox.ScintillaObject.GtkVScrollbar"style"notebookscrolledwindowscrollbar"
widget_class"*GtkNotebook.GtkVBox.ScintillaObject.GtkHScrollbar"style"notebookscrolledwindowscrollbar"
widget_class"*GtkNotebook.ThunarIconView.GtkVScrollbar"style"notebookscrolledwindowscrollbar"

style"notebookscrolledwindowscrollbar2"{
engine"pixmap"
{
image
{
function=BOX
orientation=VERTICAL
detail="trough"
file="images/scrollbar_vertical-leftopen.svg"
border={1,1,1,1}
stretch=TRUE
}
image
{
function=BOX
orientation=HORIZONTAL
detail="trough"
file="images/scrollbar_horizontal-topopen.svg"
border={1,1,1,1}
stretch=TRUE
}
image
{
function=SLIDER
state=NORMAL
orientation=VERTICAL
file="images/selection-color.svg"
stretch=FALSE
overlay_file="images/shadow.svg"
overlay_stretch=TRUE
overlay_border={1,1,1,1}
}
image
{
function=SLIDER
state=NORMAL
orientation=HORIZONTAL
file="images/selection-color.svg"
stretch=FALSE
overlay_file="images/shadow.svg"
overlay_stretch=TRUE
overlay_border={1,1,1,1}
}
image
{
function=SLIDER
state=INSENSITIVE
orientation=VERTICAL
file="images/window-color.svg"
stretch=FALSE
overlay_file="images/shadow.svg"
overlay_stretch=TRUE
overlay_border={1,1,1,1}
}
image
{
function=SLIDER
state=INSENSITIVE
orientation=HORIZONTAL
file="images/window-color.svg"
stretch=FALSE
overlay_file="images/shadow.svg"
overlay_stretch=TRUE
overlay_border={1,1,1,1}}}}
widget_class"*XfceSettingsManagerDialog.GtkVBox.GtkVBox.GtkScrolledWindow.GtkHScrollbar"style"notebookscrolledwindowscrollbar2"
widget_class"*XfceSettingsManagerDialog.GtkVBox.GtkVBox.GtkScrolledWindow.GtkVScrollbar"style"notebookscrolledwindowscrollbar2"
widget_class"*GtkPlug.GtkNotebook.GtkScrolledWindow.GtkHScrollbar"style"notebookscrolledwindowscrollbar2"
widget_class"*GtkPlug.GtkNotebook.GtkScrolledWindow.GtkVScrollbar"style"notebookscrolledwindowscrollbar2"
widget_class"*MousepadDocument.GtkHScrollbar"style"notebookscrolledwindowscrollbar2"
widget_class"*MousepadDocument.GtkVScrollbar"style"notebookscrolledwindowscrollbar2"
widget"Leafpad.GtkVBox.GtkScrolledWindow.GtkHScrollbar"style"notebookscrolledwindowscrollbar2"
widget"Leafpad.GtkVBox.GtkScrolledWindow.GtkVScrollbar"style"notebookscrolledwindowscrollbar2"
widget_class"*GtkNotebook.ThunarDetailsView.GtkVScrollbar"style"notebookscrolledwindowscrollbar2"
widget_class"*GtkNotebook.ThunarDetailsView.GtkHScrollbar"style"notebookscrolledwindowscrollbar2"
