style"tooltip"{
xthickness=2
ythickness=2
fg[NORMAL]=@text_color
fg[PRELIGHT]=@text_color
fg[SELECTED]=@text_color
fg[ACTIVE]=@text_color
fg[INSENSITIVE]=@text_color
bg[NORMAL]=@base_color
bg[PRELIGHT]=@base_color
bg[SELECTED]=@base_color
bg[ACTIVE]=@base_color
bg[INSENSITIVE]=@base_color
text[NORMAL]=@text_color
text[PRELIGHT]=@text_color
text[ACTIVE]=@text_color
text[SELECTED]=@text_color
text[INSENSITIVE]=@text_color}
widget"gtk-tooltip*"style"tooltip"
