style "lxpanelwindow"{
xthickness=0
ythickness=0
GtkWidget::shadow-type=GTK_SHADOW_NONE
GtkButton::inner-border={2,2,2,2}
GtkButton::image-spacing=5
engine"pixmap"{
image{
function=BOX
file="images/none.svg"
stretch=FALSE}
image{
function=HANDLE
file="images/none.svg"
stretch=FALSE}
image{
function=SHADOW
shadow=OUT
file="images/none.svg"
border={1,1,0,1}
stretch=TRUE}}}
widget_class "*PanelToplevel*" style "lxpanelwindow"

style"lxpanelbutton"{
xthickness=0
ythickness=0
GtkButton::inner-border={2,2,2,2}
GtkButton::shadow-type=GTK_SHADOW_NONE
GtkWidget::wide-separators=1
GtkWidget::separator-height=0
GtkWidget::separator-width=0
engine"pixmap"{
image{
function=BOX
state=INSENSITIVE
shadow=OUT
file="images/none.svg"
stretch=FALSE}
image{
function=BOX
state=NORMAL
file="images/none.svg"
stretch=FALSE}
image{
function=BOX
state=PRELIGHT
shadow=OUT
file="images/none.svg"
stretch=FALSE}
image{
function=BOX
state=PRELIGHT
shadow=IN
file="images/none.svg"
stretch=FALSE}
image{
function=BOX
state=INSENSITIVE
shadow=IN
file="images/none.svg"
stretch=FALSE}
image{
function=BOX
state=SELECTED
file="images/none.svg"
stretch=FALSE}
image{
function=BOX
state=ACTIVE
file="images/none.svg"
stretch=FALSE}
image{
detail="buttondefault"
file="images/none.svg"
stretch=FALSE}
image{
detail="focus"
file="images/none.svg"
stretch=FALSE}}}
widget_class"*PanelToplevel*Button*"style"lxpanelbutton"

style"lxpaneltask"{
xthickness=3
ythickness=3
font_name="bold"
GtkButton::inner-border={2,2,2,2}
GtkButton::shadow-type=GTK_SHADOW_NONE
GtkWidget::wide-separators=1
GtkWidget::separator-height=0
GtkWidget::separator-width=0
engine"pixmap"{
image{
function=BOX
state=INSENSITIVE
shadow=OUT
file="images/none.svg"
stretch=FALSE}
image{
function=BOX
state=NORMAL
file="images/none.svg"
stretch=FALSE}
image{
function=BOX
state=PRELIGHT
shadow=OUT
file="images/panel-task_prelight.svg"
stretch=FALSE}
image{
function=BOX
state=PRELIGHT
shadow=IN
file="images/panel-task_prelight.svg"
stretch=FALSE}
image{
function=BOX
state=INSENSITIVE
shadow=IN
file="images/none.svg"
stretch=FALSE}
image{
function=BOX
state=SELECTED
file="images/selection-color.svg"
stretch=FALSE}
image{
function=BOX
state=ACTIVE
file="images/selection-color.svg"
stretch=FALSE}
image{
detail="buttondefault"
file="images/selection-color.svg"
stretch=FALSE}
image{
detail="focus"
file="images/none.svg"
stretch=FALSE}}}
widget_class"*PanelToplevel*TaskButton*"style"lxpaneltask"
style "pcmanfm"{
xthickness=0
ythickness=0
engine"pixmap"{
image{
function=FLAT_BOX
file="images/window-color.svg"
state=NORMAL
stretch=TRUE
border={0,1,0,0}}
image{
function=FLAT_BOX
file="images/selection-color.svg"
state=SELECTED
stretch=TRUE
border={0,1,0,0}}}}
widget_class "*FmSidePane*"style "pcmanfm"

style"lxpanelbold"{
xthickness=0
ythickness=0
font_name="bold"}
widget_class"*PanelToplevel*TaskButton*"style"lxpanelbold"
widget"*TaskButton*GtkLabel"style"lxpanelbold"
widget"*taskbar*"style"lxpanelbold"
widget"*dclock*"style"lxpanelbold"
widget"*PanelIconGrid*"style"lxpanelbold"
